### PR TITLE
灌水react项目

### PR DESCRIPTION
**Pull request by knoxnoe**
在根目录下新建web/fleashop-fronter,放整个前端项目

### CODE REVIEW

**Review by qiangyt — CHANGES_REQUESTED** [review]
.DS_Store file should not be in git.
And so, should be in .gitignore

**Review by qiangyt — CHANGES_REQUESTED** [review]
web/fleashop-fronter/.eslintcache should not be in git, since it has personal settings, for ex. /Users/noe....

**Review by qiangyt — COMMENTED** [review]
Great, what I'm thinking is also to begin from a cra-generated frontend project

**Comment by knoxnoe** [comment]
.gitignore添加了不需要git控制的文件

**Comment by qiangyt** [comment]
@knoxnoe , 不止一个.DS_Store, 几乎每个文件夹下都有，譬如 
- server/src/.DS_Store
- server/src/main/.DS_Store
- server/src/main/java/DS_Store
- server/src/main/java/org/.DS_Store

**Comment by knoxnoe** [comment]
ok

**Review by suntoe — APPROVED** [review]

**Review by qiangyt — APPROVED** [review]

**Pull request merged**
